version: '2'
services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:10.3.1
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    network_mode: bridge
