version: '2'
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:9.6-alpine
    restart: always
    #volumes:
    #  - "/opt/postgis/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    network_mode: bridge
